version: '3'
services:
    frontend:
        # restart: always
        build: ./frontend
        ports:
            - "4200:4200"
    #     volumes:
    #         - ./frontend/mediaq/build:/app/build
    #         - ./frontend/mediaq/src:/app/src
    #         - ./frontend/mediaq/public:/app/public
    #     restart: always
    backend:
        build: ./backend
        ports:
            - "5000:80"
        volumes:
            - ./backend:/app/backend
        image: arkareem/pdf-mobile-integration-backend
    # database:
    #     build: ./database
    #     ports:
    #         - "6379:6379"
    #     volumes:
    #         - ./database/redis_data:/data