version: '3'

volumes:
    exclude_node_modules:

services:
    frontend:
        build: 
            args: 
                APP_ENV: dev  # dev or prod
        volumes:
            - ./frontend/app/:/app/frontend/
            - exclude_node_modules:/app/frontend/node_modules/
    backend:
        volumes:
            - ./backend:/app/backend
