version: '3'

services:
    frontend:
        build: 
            context: ./frontend
            args: 
                APP_ENV: prod  # dev or prod
    backend:
        build: 
            context: ./backend
            args: 
                APP_ENV: prod  # dev or prod
