version: '3'
services:
    frontend:
        build: 
            context: ./frontend
            args: 
                APP_ENV: dev  # dev or prod
        ports:
            - "4201:4200"
    #     volumes:
    #         - ./frontend/mediaq/build:/app/build
    #         - ./frontend/mediaq/src:/app/src
    #         - ./frontend/mediaq/public:/app/public
    #     restart: always
    backend:
        build: ./backend
        ports:
            - "5001:8080"
        volumes:
            - ./backend:/app/backend
        image: arkareem/pdf-mobile-integration-backend
    # database:
    #     build: ./database
    #     ports:
    #         - "6379:6379"
    #     volumes:
    #         - ./database/redis_data:/data