version: '3'

services:
    frontend:
        build: 
            args: 
                APP_ENV: prod  # dev or prod
    backend:
        build: 
            args: 
                APP_ENV: prod  # dev or prod
